INFO 2025-07-07 16:08:15,670 autoreload 35365 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:08:34,498 autoreload 35624 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:09:51,282 autoreload 36357 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:11:13,097 autoreload 37130 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:12:31,021 autoreload 37961 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:15:48,001 autoreload 39665 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:16:43,807 autoreload 40218 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:22:54,268 autoreload 44444 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:23:19,170 autoreload 44813 8599723776 Watching for file changes with StatReloader
ERROR 2025-07-07 16:23:20,708 log 44813 6163214336 Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 226, in get
    context = self.get_context_data(**kwargs)
  File "/Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/core/views.py", line 25, in get_context_data
    context['residents_count'] = Building.objects.aggregate(
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        total=Sum('apartments__apartment_count')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )['total'] or 0
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py", line 588, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py", line 460, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
        self, allow_joins=True, reuse=None, summarize=True
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/aggregates.py", line 63, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/expressions.py", line 300, in resolve_expression
    expr.resolve_expression(query, allow_joins, reuse, summarize)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/expressions.py", line 902, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py", line 2062, in resolve_ref
    transform = join_info.transform_function(targets[0], final_alias)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1920, in transform
    return self.try_transform(wrapped, name)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1455, in try_transform
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Unsupported lookup 'apartment_count' for BigAutoField or join on the field not permitted.
ERROR 2025-07-07 16:23:20,711 basehttp 44813 6163214336 "GET / HTTP/1.1" 500 126807
INFO 2025-07-07 17:18:01,588 autoreload 71463 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 17:18:11,923 autoreload 71710 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 17:18:14,748 basehttp 71710 6155956224 "GET / HTTP/1.1" 200 22186
INFO 2025-07-07 17:18:14,848 basehttp 71710 6223261696 "GET /static/images/logo-sm.png HTTP/1.1" 200 3568
INFO 2025-07-07 17:18:14,850 basehttp 71710 6206435328 "GET /static/images/logo.png HTTP/1.1" 200 5428
INFO 2025-07-07 17:18:14,851 basehttp 71710 6155956224 "GET /static/css/vendor.min.css HTTP/1.1" 200 37938
INFO 2025-07-07 17:18:14,856 basehttp 71710 6189608960 "GET /static/css/icons.min.css HTTP/1.1" 200 376013
INFO 2025-07-07 17:18:14,857 basehttp 71710 6172782592 "GET /static/css/app.min.css HTTP/1.1" 200 440639
INFO 2025-07-07 17:18:14,868 basehttp 71710 6172782592 "GET /static/images/logo-dark.png HTTP/1.1" 200 5502
INFO 2025-07-07 17:18:14,875 basehttp 71710 6155956224 "GET /static/js/app.js HTTP/1.1" 200 17575
WARNING 2025-07-07 17:18:14,877 basehttp 71710 6206435328 "GET /static/images/building.svg HTTP/1.1" 404 1984
INFO 2025-07-07 17:18:14,884 basehttp 71710 6189608960 "GET /static/js/vendor.min.js HTTP/1.1" 200 534826
INFO 2025-07-07 17:18:15,037 basehttp 71710 6189608960 "GET /static/images/body-bg-light.jpg HTTP/1.1" 200 163957
INFO 2025-07-07 17:18:15,128 basehttp 71710 6189608960 "GET /static/fonts/remixicon44dd.woff2?t=1730118419915 HTTP/1.1" 200 174156
WARNING 2025-07-07 17:18:15,323 log 71710 6189608960 Not Found: /api/badges/
WARNING 2025-07-07 17:18:15,325 log 71710 6155956224 Not Found: /notifications/ajax/list/
WARNING 2025-07-07 17:18:15,325 basehttp 71710 6189608960 "GET /api/badges/ HTTP/1.1" 404 5560
WARNING 2025-07-07 17:18:15,325 basehttp 71710 6155956224 "GET /notifications/ajax/list/ HTTP/1.1" 404 6903
INFO 2025-07-07 17:18:15,372 basehttp 71710 6189608960 "GET /static/images/favicon.ico HTTP/1.1" 200 109599
INFO 2025-07-07 17:44:20,599 autoreload 86692 8599723776 Watching for file changes with StatReloader
WARNING 2025-07-07 17:44:34,584 log 86692 6194868224 Not Found: /api/
WARNING 2025-07-07 17:44:34,585 basehttp 86692 6194868224 "GET /api/ HTTP/1.1" 404 5539
INFO 2025-07-07 17:46:00,443 autoreload 86692 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/packages/models.py changed, reloading.
INFO 2025-07-07 17:46:01,353 autoreload 87480 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 17:47:05,745 autoreload 87480 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/apartment_project/settings.py changed, reloading.
INFO 2025-07-07 17:47:06,543 autoreload 88078 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 17:54:36,158 autoreload 93018 8599723776 Watching for file changes with StatReloader
WARNING 2025-07-07 17:54:49,539 log 93018 6156611584 Not Found: /api/products/
WARNING 2025-07-07 17:54:49,539 basehttp 93018 6156611584 "GET /api/products/ HTTP/1.1" 404 6673
WARNING 2025-07-07 17:54:53,302 log 93018 6156611584 Not Found: /api/
WARNING 2025-07-07 17:54:53,303 basehttp 93018 6156611584 "GET /api/ HTTP/1.1" 404 6646
WARNING 2025-07-07 17:54:53,731 log 93018 6156611584 Not Found: /api/
WARNING 2025-07-07 17:54:53,732 basehttp 93018 6156611584 "GET /api/ HTTP/1.1" 404 6646
INFO 2025-07-07 17:55:09,793 basehttp 93018 6173437952 "GET /api/docs HTTP/1.1" 301 0
INFO 2025-07-07 17:55:09,799 basehttp 93018 6190264320 "GET /api/docs/ HTTP/1.1" 200 4657
ERROR 2025-07-07 17:55:13,509 log 93018 6190264320 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 256, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 112, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1397, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1453, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1048, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 684, in _map_serializer_field
    component = self.resolve_serializer(field, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1042, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `description` is not valid for model `Building`.
ERROR 2025-07-07 17:55:13,512 basehttp 93018 6190264320 "GET /api/schema/ HTTP/1.1" 500 213303
ERROR 2025-07-07 17:55:13,606 log 93018 6190264320 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 256, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 112, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1397, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1453, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1048, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 684, in _map_serializer_field
    component = self.resolve_serializer(field, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1042, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `description` is not valid for model `Building`.
ERROR 2025-07-07 17:55:13,608 basehttp 93018 6190264320 "GET /api/schema/ HTTP/1.1" 500 213303
ERROR 2025-07-07 17:55:27,091 log 93018 6156611584 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 256, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 112, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1397, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1453, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1048, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 684, in _map_serializer_field
    component = self.resolve_serializer(field, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1042, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `description` is not valid for model `Building`.
ERROR 2025-07-07 17:55:27,093 basehttp 93018 6156611584 "GET /api/schema/ HTTP/1.1" 500 213811
ERROR 2025-07-07 17:55:27,561 log 93018 6156611584 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 256, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 112, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1397, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1453, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1048, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 684, in _map_serializer_field
    component = self.resolve_serializer(field, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1042, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `description` is not valid for model `Building`.
ERROR 2025-07-07 17:55:27,563 basehttp 93018 6156611584 "GET /api/schema/ HTTP/1.1" 500 213537
INFO 2025-07-07 17:56:11,814 autoreload 93018 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/buildings/serializers.py changed, reloading.
INFO 2025-07-07 17:56:12,683 autoreload 93827 8599723776 Watching for file changes with StatReloader
ERROR 2025-07-07 17:56:15,877 log 93827 6170652672 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 256, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/utils.py", line 451, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 112, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1397, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1453, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1042, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `created_at` is not valid for model `Package`.
ERROR 2025-07-07 17:56:15,881 basehttp 93827 6170652672 "GET /api/schema/ HTTP/1.1" 500 192403
ERROR 2025-07-07 17:56:27,095 log 93827 6187479040 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 256, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/utils.py", line 451, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 112, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1397, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1453, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1042, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `created_at` is not valid for model `Package`.
ERROR 2025-07-07 17:56:27,097 basehttp 93827 6187479040 "GET /api/schema/ HTTP/1.1" 500 192403
ERROR 2025-07-07 17:57:07,043 log 93827 6170652672 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 256, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/utils.py", line 451, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 112, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1397, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1453, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1042, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `created_at` is not valid for model `Package`.
ERROR 2025-07-07 17:57:07,045 basehttp 93827 6170652672 "GET /api/schema/ HTTP/1.1" 500 192403
ERROR 2025-07-07 17:57:13,831 log 93827 6204305408 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 256, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/utils.py", line 451, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 112, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1397, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1453, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1042, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `created_at` is not valid for model `Package`.
ERROR 2025-07-07 17:57:13,833 basehttp 93827 6204305408 "GET /api/schema/ HTTP/1.1" 500 192403
INFO 2025-07-07 17:57:23,744 autoreload 93827 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/buildings/api_urls.py changed, reloading.
INFO 2025-07-07 17:57:24,666 autoreload 94448 8599723776 Watching for file changes with StatReloader
ERROR 2025-07-07 17:57:49,651 log 94448 6156840960 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 256, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/utils.py", line 451, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 112, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1397, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1453, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1042, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `created_at` is not valid for model `Package`.
ERROR 2025-07-07 17:57:49,653 basehttp 94448 6156840960 "GET /api/schema/ HTTP/1.1" 500 191735
INFO 2025-07-07 17:57:49,766 autoreload 94448 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/apartment_project/api_urls.py changed, reloading.
INFO 2025-07-07 17:57:50,408 autoreload 94658 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 17:58:18,684 autoreload 94658 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/buildings/api_views.py changed, reloading.
INFO 2025-07-07 17:58:19,340 autoreload 94888 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 17:58:21,867 autoreload 95111 8599723776 Watching for file changes with StatReloader
ERROR 2025-07-07 17:58:50,832 log 94888 6128578560 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/generators.py", line 256, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/utils.py", line 451, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 112, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1397, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1453, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1648, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 949, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1042, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `created_at` is not valid for model `Package`.
ERROR 2025-07-07 17:58:50,836 basehttp 94888 6128578560 "GET /api/schema/ HTTP/1.1" 500 192432
INFO 2025-07-07 17:59:27,447 autoreload 94888 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/packages/serializers.py changed, reloading.
INFO 2025-07-07 17:59:28,278 autoreload 95732 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 17:59:55,398 autoreload 95732 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/caretaker/models.py changed, reloading.
INFO 2025-07-07 17:59:56,040 autoreload 95973 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 18:00:01,659 basehttp 95973 6159052800 "GET /api/schema/ HTTP/1.1" 200 158686
INFO 2025-07-07 18:00:12,086 autoreload 95973 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/packages/serializers.py changed, reloading.
INFO 2025-07-07 18:00:12,764 autoreload 96124 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 18:01:26,491 autoreload 96124 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/packages/api_views.py changed, reloading.
INFO 2025-07-07 18:01:27,443 autoreload 97015 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 18:02:03,985 autoreload 97015 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/packages/api_views.py changed, reloading.
INFO 2025-07-07 18:02:04,807 autoreload 97348 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 18:11:35,864 autoreload 3152 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 18:11:38,558 basehttp 3152 6170898432 "GET /api/schema/ HTTP/1.1" 200 158916
INFO 2025-07-07 18:12:30,879 basehttp 3152 6170898432 "GET /api/schema/ HTTP/1.1" 200 158916
INFO 2025-07-07 18:12:54,401 autoreload 3152 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/packages/models.py changed, reloading.
INFO 2025-07-07 18:12:55,449 autoreload 4373 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 18:25:56,879 autoreload 9064 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 18:25:58,977 basehttp 9064 6160576512 "GET / HTTP/1.1" 200 22186
WARNING 2025-07-07 18:25:59,086 basehttp 9064 6160576512 "GET /static/images/building.svg HTTP/1.1" 404 1984
WARNING 2025-07-07 18:25:59,424 log 9064 6177402880 Not Found: /api/badges/
WARNING 2025-07-07 18:25:59,426 log 9064 6160576512 Not Found: /notifications/ajax/list/
WARNING 2025-07-07 18:25:59,426 basehttp 9064 6177402880 "GET /api/badges/ HTTP/1.1" 404 6667
WARNING 2025-07-07 18:25:59,427 basehttp 9064 6160576512 "GET /notifications/ajax/list/ HTTP/1.1" 404 6898
INFO 2025-07-07 18:26:01,511 basehttp 9064 6160576512 "GET /users/login/ HTTP/1.1" 200 20627
WARNING 2025-07-07 18:26:01,533 basehttp 9064 6160576512 "GET /static/images/logo-light.png HTTP/1.1" 404 1990
WARNING 2025-07-07 18:26:01,536 log 9064 6194229248 Not Found: /notifications/ajax/list/
WARNING 2025-07-07 18:26:01,539 log 9064 6177402880 Not Found: /api/badges/
WARNING 2025-07-07 18:26:01,541 basehttp 9064 6194229248 "GET /notifications/ajax/list/ HTTP/1.1" 404 6898
WARNING 2025-07-07 18:26:01,542 basehttp 9064 6177402880 "GET /api/badges/ HTTP/1.1" 404 6667
INFO 2025-07-07 18:26:05,315 basehttp 9064 6160576512 "GET /users/register/ HTTP/1.1" 200 21048
WARNING 2025-07-07 18:26:05,330 basehttp 9064 6160576512 "GET /static/images/logo-light.png HTTP/1.1" 404 1990
WARNING 2025-07-07 18:26:05,350 log 9064 6177402880 Not Found: /api/badges/
WARNING 2025-07-07 18:26:05,353 log 9064 6194229248 Not Found: /notifications/ajax/list/
WARNING 2025-07-07 18:26:05,353 basehttp 9064 6177402880 "GET /api/badges/ HTTP/1.1" 404 6667
WARNING 2025-07-07 18:26:05,353 basehttp 9064 6194229248 "GET /notifications/ajax/list/ HTTP/1.1" 404 6898
INFO 2025-07-07 18:27:45,029 autoreload 9064 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/core/views.py changed, reloading.
INFO 2025-07-07 18:27:46,174 autoreload 9974 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 18:28:15,412 autoreload 9974 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/notifications/views.py changed, reloading.
INFO 2025-07-07 18:28:16,148 autoreload 10249 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 18:28:39,033 autoreload 10249 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/core/urls.py changed, reloading.
INFO 2025-07-07 18:28:39,672 autoreload 10443 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 18:28:54,051 basehttp 10443 6196293632 "GET / HTTP/1.1" 200 22186
WARNING 2025-07-07 18:28:54,135 basehttp 10443 6196293632 "GET /static/images/building.svg HTTP/1.1" 404 1984
WARNING 2025-07-07 18:28:54,189 log 10443 6213120000 Not Found: /api/badges/
WARNING 2025-07-07 18:28:54,193 log 10443 6196293632 Not Found: /notifications/ajax/list/
WARNING 2025-07-07 18:28:54,193 basehttp 10443 6213120000 "GET /api/badges/ HTTP/1.1" 404 6667
WARNING 2025-07-07 18:28:54,195 basehttp 10443 6196293632 "GET /notifications/ajax/list/ HTTP/1.1" 404 6898
WARNING 2025-07-07 18:28:59,060 log 10443 6196293632 Not Found: /api/
WARNING 2025-07-07 18:28:59,060 basehttp 10443 6196293632 "GET /api/ HTTP/1.1" 404 6646
WARNING 2025-07-07 18:29:02,047 log 10443 6196293632 Not Found: /ap/docs
WARNING 2025-07-07 18:29:02,047 basehttp 10443 6196293632 "GET /ap/docs HTTP/1.1" 404 5543
INFO 2025-07-07 18:29:04,853 autoreload 10443 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/notifications/urls.py changed, reloading.
INFO 2025-07-07 18:29:05,481 autoreload 10665 8599723776 Watching for file changes with StatReloader
WARNING 2025-07-07 18:29:05,902 log 10665 6192181248 Not Found: /ap/docs/
WARNING 2025-07-07 18:29:05,902 basehttp 10665 6192181248 "GET /ap/docs/ HTTP/1.1" 404 5546
INFO 2025-07-07 18:29:36,673 autoreload 10665 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/apartment_project/urls.py changed, reloading.
INFO 2025-07-07 18:29:37,402 autoreload 10941 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 18:30:35,713 autoreload 10941 8599723776 /Users/umutaraz/Desktop/Tüm Projelerim/ApartmentManagement/apartment_project/urls.py changed, reloading.
INFO 2025-07-07 18:30:36,506 autoreload 11433 8599723776 Watching for file changes with StatReloader
