INFO 2025-07-07 16:08:15,670 autoreload 35365 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:08:34,498 autoreload 35624 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:09:51,282 autoreload 36357 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:11:13,097 autoreload 37130 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:12:31,021 autoreload 37961 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:15:48,001 autoreload 39665 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:16:43,807 autoreload 40218 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:22:54,268 autoreload 44444 8599723776 Watching for file changes with StatReloader
INFO 2025-07-07 16:23:19,170 autoreload 44813 8599723776 Watching for file changes with StatReloader
ERROR 2025-07-07 16:23:20,708 log 44813 6163214336 Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/views/generic/base.py", line 226, in get
    context = self.get_context_data(**kwargs)
  File "/Users/umutaraz/Desktop/TuÌˆm Projelerim/ApartmentManagement/core/views.py", line 25, in get_context_data
    context['residents_count'] = Building.objects.aggregate(
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        total=Sum('apartments__apartment_count')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )['total'] or 0
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py", line 588, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py", line 460, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
        self, allow_joins=True, reuse=None, summarize=True
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/aggregates.py", line 63, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/expressions.py", line 300, in resolve_expression
    expr.resolve_expression(query, allow_joins, reuse, summarize)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/expressions.py", line 902, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py", line 2062, in resolve_ref
    transform = join_info.transform_function(targets[0], final_alias)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1920, in transform
    return self.try_transform(wrapped, name)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1455, in try_transform
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Unsupported lookup 'apartment_count' for BigAutoField or join on the field not permitted.
ERROR 2025-07-07 16:23:20,711 basehttp 44813 6163214336 "GET / HTTP/1.1" 500 126807
